spring:
  application:
    name: spring-demo3
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatis_test?characterEncoding=utf8&useSSL=false
    username: root
    password: ccc123
    driver-class-name: com.mysql.cj.jdbc.Driver